# Generated by Django 5.0.2 on 2024-04-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name': 'Atração', 'verbose_name_plural': 'Atrações'},
        ),
    ]
