# Generated by Django 5.0.2 on 2024-04-22 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacao', '0002_alter_avaliacao_options'),
        ('comentario', '0002_alter_comentario_options'),
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('aprovado', models.BooleanField(default=False)),
                ('campo_teste', models.CharField(blank=True, max_length=100, null=True)),
                ('avaliacoes', models.ManyToManyField(to='avaliacao.avaliacao')),
                ('comentarios', models.ManyToManyField(to='comentario.comentario')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco')),
            ],
            options={
                'verbose_name': 'Ponto Turístico',
                'verbose_name_plural': 'Pontos Turísticos',
            },
        ),
    ]
