# Generated by Django 5.0.2 on 2024-03-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'verbose_name': 'Ponto Turístico', 'verbose_name_plural': 'Pontos Turísticos'},
        ),
    ]
