# Generated by Django 5.0.2 on 2024-05-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_docidentificacao_pontoturistico_foto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docidentificacao',
            options={'verbose_name': 'Documento de Identificação', 'verbose_name_plural': 'Documentos de Identificação'},
        ),
    ]
